build_from:
  aarch64: "ghcr.io/hassio-addons/base:19.0.0"
  amd64: "ghcr.io/hassio-addons/base:19.0.0"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Resticprofile Backup"
  org.opencontainers.image.description:
    "Home Assistant Add-on that can run scheduled resticprofile Backups."
  org.opencontainers.image.source: "https://github.com/danez/hassio-addons/tree/main/resticprofile-backup"
  org.opencontainers.image.licenses: "MIT"
args:
  BUILD_RESTIC_VERSION: "0.18.1"
  BUILD_RESTICPROFILE_VERSION: "0.32.0"
  BUILD_RCLONE_VERSION: "1.72.1"
