labels:
  org.opencontainers.image.title: "Home Assistant App: Resticprofile Backup"
  org.opencontainers.image.description:
    "Home Assistant App that can run scheduled resticprofile Backups."
  org.opencontainers.image.source: "https://github.com/danez/hassio-addons/tree/main/resticprofile-backup"
  org.opencontainers.image.licenses: "MIT"
args:
  BUILD_RESTIC_VERSION: "0.18.1"
  BUILD_RESTICPROFILE_VERSION: "0.32.0"
  BUILD_RCLONE_VERSION: "1.73.0"
