build_from:
  aarch64: "ghcr.io/hassio-addons/base:18.1.2"
  amd64: "ghcr.io/hassio-addons/base:18.1.2"
  armhf: "ghcr.io/hassio-addons/base:18.1.2"
  armv7: "ghcr.io/hassio-addons/base:18.1.2"
  i386: "ghcr.io/hassio-addons/base:18.1.2"
codenotary:
  signer: notary@tschinder.de
  base_image: notary@home-assistant.io
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Resticprofile Backup"
  org.opencontainers.image.description:
    "Home Assistant Add-on that can run scheduled resticprofile Backups."
  org.opencontainers.image.source: "https://github.com/danez/hassio-addons/tree/main/resticprofile-backup"
  org.opencontainers.image.licenses: "MIT"
args:
  BUILD_RESTIC_VERSION: "0.18.1"
  BUILD_RESTICPROFILE_VERSION: "0.32.0"
  BUILD_RCLONE_VERSION: "1.71.1"
