name: Resticprofile Backup
version: "1.2.1"
slug: resticprofile-backup
description: Allows resticprofile configs for custom backups
url: "https://github.com/danez/hassio-addons/tree/main/resticprofile-backup"
codenotary: notary@tschinder.de
hassio_api: true
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - type: addon_config
    read_only: False
    path: /config
  - type: addons
  - type: all_addon_configs
    path: /addon_configs
  - type: backup
  - type: data
  - type: homeassistant_config
  - type: media
  - type: share
    read_only: False
  - type: ssl
options:
  smb_shares: []
schema:
  smb_shares:
    - host: "str"
      local: "str"
      username: "str?"
      password: "str?"
      smb_version: "str?"
image: "ghcr.io/danez/{arch}-addon-resticprofile-backup"
