name: Resticprofile Backup
version: "1.3.1"
slug: resticprofile-backup
description: Allows resticprofile configs for custom backups
url: "https://github.com/danez/hassio-addons/tree/main/resticprofile-backup"
codenotary: notary@tschinder.de
hassio_api: true
udev: true
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
devices:
  - /dev/sda
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
  - /dev/sde
  - /dev/sdf
  - /dev/sdg
  - /dev/nvme0
  - /dev/nvme0n1
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/nvme0n1p3
  - /dev/nvme1n1
  - /dev/nvme1n1p1
  - /dev/nvme1n1p2
  - /dev/nvme1n1p3
  - /dev/nvme2n1
  - /dev/nvme2n1p1
  - /dev/nvme2n1p2
  - /dev/nvme2n1p3
  - /dev/sda1
  - /dev/sdb1
  - /dev/sdc1
  - /dev/sdd1
  - /dev/sde1
  - /dev/sdf1
  - /dev/sdg1
  - /dev/sda2
  - /dev/sdb2
  - /dev/sdc2
  - /dev/sdd2
  - /dev/sde2
  - /dev/sdf2
  - /dev/sdg2
  - /dev/sda3
  - /dev/sdb3
  - /dev/sda4
  - /dev/sdb4
  - /dev/sda5
  - /dev/sda6
  - /dev/sda7
  - /dev/sda8
map:
  - type: addon_config
    read_only: False
    path: /config
  - type: addons
  - type: all_addon_configs
    path: /addon_configs
  - type: backup
  - type: data
  - type: homeassistant_config
  - type: media
  - type: share
    read_only: False
  - type: ssl
options:
  smb_shares: []
schema:
  localdisks: "str?"
  smb_shares:
    - host: "str"
      local: "str"
      username: "str?"
      password: "str?"
      smb_version: "str?"
image: "ghcr.io/danez/{arch}-addon-resticprofile-backup"
