build_from:
  aarch64: "ghcr.io/hassio-addons/base:19.0.0"
  amd64: "ghcr.io/hassio-addons/base:19.0.0"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: AFFiNE"
  org.opencontainers.image.description:
    "Home Assistant Add-on that runs AFFiNE self-hosted."
  org.opencontainers.image.source: "https://github.com/danez/hassio-addons/tree/main/affine"
  org.opencontainers.image.licenses: "MIT"
args:
  BUILD_AFFINE_VERSION: "0.26.2"
