build_from:
  aarch64: ""
  amd64: ""
labels:
  org.opencontainers.image.title: "Home Assistant App: AFFiNE"
  org.opencontainers.image.description:
    "Home Assistant App that runs AFFiNE self-hosted."
  org.opencontainers.image.source: "https://github.com/danez/hassio-addons/tree/main/affine"
  org.opencontainers.image.licenses: "MIT"
args:
  BUILD_AFFINE_VERSION: "0.26.2"
